### ISSUE TITLE
TL;PL

### ISSUE THREAD

**Issue by Pale-whale** [ThomFree/Pizzia#1]
Trop long; Pas lu.

**Comment by ThomFree** [comment]
Alors, pour ceux qui n'aiment pas la lecture, vous pouvez facilement comprendre notre API avec :
- [le guide](https://github.com/ThomFree/Pizzia/blob/master/docs/guide.md)
- [les exemples de module](https://github.com/ThomFree/Pizzia/tree/master/mods)

Merci @Mooris pour cette question constructive xD

**Comment by Xwilarg** [comment]
Hey your guide.md file is only in french, would there be an english version ?

**Comment by Pale-whale** [comment]
J'ai essayer de regarder un exemple (i.e https://github.com/ThomFree/Pizzia/tree/master/mods/hard-DecryptionEncryption) Et je ne trouve pas plus d'informations, Je suis perdu je ne comprends pas comment marche votre ```API``` :|
