### ISSUE TITLE
Delivery error

### ISSUE THREAD

**Issue by Pale-whale** [ThomFree/Pizzia#4]
I tried to use your API but the delivery gut never came with the pizza :/ I'm a reallu hungry dev and your readme told me pizia would be for me but plz fix

**Comment by Mooris** [comment]
Will vote for dems :(

**Comment by Mooris** [comment]
https://sikke.fi/videos/watch/a102285b-d790-44f0-a6c1-04100d4e364b

**Comment by ThomFree** [comment]
La censure s'applique 🙄
