### ISSUE TITLE
A bas la censure

### ISSUE THREAD

**Issue by Pale-whale** [ThomFree/Pizzia#6]
Puisqu'ici c'est la censure je pense qu'un petit tutorial s'impose.
https://sikke.fi/videos/watch/a102285b-d790-44f0-a6c1-04100d4e364b
Gogo revolutioner

**Comment by ThomFree** [comment]
Nos méthodes d'évaluation des Issues est en cours de changement, merci de votre compréhension.

**Comment by Pale-whale** [comment]
@Emeraude J'ai essayer ca marche pas, comment tu fait du coup ?

**Comment by ThomFree** [comment]
Nous n'avons pas compris votre demande, merci de détailler votre problème ;)

**Comment by Xwilarg** [comment]
@TheIndra55 Come help us

**Comment by Pale-whale** [comment]
Bonjour, je m'insurge actuellement contre votre gestion de repo car lorsqu'un comment est posté @ThomFree supprime instantanement ainsi nous ne pouvont pas nous exprimer, ceci est un manquement fondamental aux droits de l'homme et a la constitution.

**Comment by TheIndra55** [comment]
Welp what´s this
